apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-backup
spec:
  schedule: "0 2 * * *"  # Run at 2 AM daily
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-backup
            image: postgres:latest
            env:
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-credentials
                    key: password
            command:
            - /bin/sh
            - -c
            - |
              pg_dump -h db -U $POSTGRES_USER $POSTGRES_DB | gzip > /backup/backup-$(date +%Y-%m-%d).sql.gz
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: backup-pvc
